#Config File example
save_dir: workspace/gray_stereo_multi_branch_220448
model:
  weight_averager:
    name: ExpMovingAverager
    decay: 0.9998
  arch:
    name: NanoDetPlus
    detach_epoch: 10
    backbone:
      name: ShuffleNetV2
      model_size: 0.5x
      out_stages: [2,3,4]
      width_batch_size: 2
      height_batch_size: 1
      image_channels: 1
      activation: LeakyReLU
    fpn:
      name: GhostPAN
      in_channels: [48, 96, 192]
      out_channels: 96
      kernel_size: 3
      num_extra_level: 1
      use_depthwise: True
      activation: LeakyReLU
    head:
      name: NanoDetPlusHead
      num_classes: 1
      input_channel: 96
      width_branch_size: 2
      height_branch_size: 1
      feat_channels: 96
      stacked_convs: 2
      kernel_size: 3
      strides: [8, 16, 32, 64]
      activation: LeakyReLU
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
    # Auxiliary head, only use in training time.
    aux_head:
      name: SimpleConvHead
      num_classes: 1
      input_channel: 192
      width_branch_size: 2
      height_branch_size: 1
      feat_channels: 192
      stacked_convs: 4
      strides: [8, 16, 32, 64]
      activation: LeakyReLU
      reg_max: 7

data:
  train:
    name: CocoDataset
    img_path: /root/autodl-tmp/sim_data_stereo_ann/train
    ann_path: /root/autodl-tmp/sim_data_stereo_ann/train.json
    input_size: [896, 256] # [w, h]
    keep_ratio: False
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[0.8, 1.2], [0.8, 1.2]]
      rotation: 0
      shear: 0
      # translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [0.6, 1.4]
      saturation: [0.5, 1.2]
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395], False]
  val:
    name: CocoDataset
    img_path: /root/autodl-tmp/real_data_stereo_ann/data
    ann_path: /root/autodl-tmp/real_data_stereo_ann/annotations.json
    input_size: [896, 256] # [w, h]
    keep_ratio: False
    pipeline:
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395], False]

device:
  gpu_ids: [0]
  workers_per_gpu: 12
  batchsize_per_gpu: 190
schedule:
#  resume:
#  load_model: /home/ebook/tao_workspace/nanodet_tao/demo/nanodet-plus-m_416_checkpoint.ckpt
  optimizer:
    name: AdamW
    lr: 0.001
    weight_decay: 0.05
  warmup:
    name: linear
    steps: 500
    ratio: 0.0001
  total_epochs: 150
  lr_schedule:
    name: CosineAnnealingLR
    T_max: 200
    eta_min: 0.00005
  val_intervals: 10
grad_clip: 35
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP
log:
  interval: 50

class_names: ['controller']